sonar.projectKey=python-webapp-cicd-openshift
sonar.projectName=Python WebApp CICD OpenShift
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
