auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  chunk_idle_period: 5m
  max_chunk_age: 1h
schema_config:
  configs:
  - from: 2024-01-01
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
