apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-webapp-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/python-webapp-cicd-openshift
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: python-webapp-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
