---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-webapp-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zeeshanahmad12/OpenShift-GitOps-Engine
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: python-webapp-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
